exclude: '^$'
fail_fast: false
default_language_version:
    python: python3.8
repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args: [--max-line-length=120]
            language_version: python3.8
    - repo: https://github.com/ambv/black
      rev: 21.6b0
      hooks:
          - id: black
            args: [--line-length=120, --target-version=py38]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-symlinks
          - id: check-ast
          - id: check-merge-conflict
          - id: debug-statements
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.902
      hooks:
          - id: mypy
            args: [--ignore-missing-import]
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.7.2.1
      hooks:
          - id: shellcheck
