exclude: '^$'
fail_fast: false
default_language_version:
    python: python3.8
repos:
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args: [--max-line-length=120]
            language_version: python3.8
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--line-length=120, --target-version=py38]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-symlinks
          - id: check-ast
          - id: check-merge-conflict
          - id: debug-statements
    # sadly, mypy does not really like when we run it on several independant folders, see those issues on the same topic :
    #   https://github.com/python/mypy/issues/4008
    #   https://github.com/python/mypy/issues/10428
    # a workaround would be to customize mypy run (to execute several independant mypy) but I don't want to do this
    # (apart from the complexity, it would probably need to explicitly define the poc' folders , or to use discovering rules)
    # as I still want to keep pocs independant from each other, the simplest choice is sadly to disable mypy pre-commit check :-(
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v0.902
    #   hooks:
    #       - id: mypy
    #         args: [--ignore-missing-import]
    #         # in some POCs, mypy errors are DESIRED (to illustrate mypy behaviour), so we skip mypy for them :
    #         exclude: "\
    #                   python/type_checking/poc01_when_does_mypy_actually_run/poc_with_annotated_main.py|\
    #                   python/type_checking/poc02_using_newtype/poc.py|\
    #                   python/type_checking/poc03_using_newtype_bis/poc.py|\
    #                   python/type_checking/poc04_abstractmethod_static_type_checking/poc.py|\
    #                   python/type_checking/poc05_abstractmethod_runtime_behaviour/poc.py|\
    #                   python/type_checking/poc08_interface3_using_metaclass_to_define_an_interface/library.py|\
    #                   python/type_checking/poc09_interface4_using_abcmeta/library.py\
    #           "
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.8.0.4
      hooks:
          - id: shellcheck
            args: [-x]
    - repo: https://github.com/doublify/pre-commit-clang-format
      rev: 62302476d0da01515660132d76902359bed0f782
      hooks:
          - id: clang-format
            types_or: [c++,c]
